# Generated by Django 4.2.16 on 2024-11-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_subscriber_groups_subscriber_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
